export interface Product {
  id: string;
  name: string;
  image: string;
  price: number;
  designer: string;
  category: string;
  subcategory?: string;
  gender?: 'women' | 'men' | 'kids' | 'unisex';
  occasion?: string;
  isNew?: boolean;
  isFeatured?: boolean;
  sizes?: string[];
  colors?: string[];
  description?: string;
}

// Women's Clothing Products
export const womenClothingProducts: Product[] = [
  {
    id: 'wcloth-1',
    name: 'Beautiful African Print Dress',
    image: '/images/product-clothing-1.jpg',
    price: 52000,
    designer: 'ADIRE BUTIK',
    category: 'Clothing',
    subcategory: 'Dresses',
    gender: 'women',
    isNew: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Orange', 'Brown'],
    description: 'A stunning African print dress featuring vibrant ankara fabric with geometric patterns.',
  },
  {
    id: 'wcloth-2',
    name: 'Elegant Boubou Gown',
    image: '/images/category-boubous.jpg',
    price: 65000,
    designer: 'IDOWU COUTURE AND WEARS',
    category: 'Clothing',
    subcategory: 'Boubous',
    gender: 'women',
    isNew: true,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Royal Blue', 'Gold'],
  },
  {
    id: 'wcloth-3',
    name: 'Vibrant Dashiki Top',
    image: '/images/product-clothing-3.jpg',
    price: 50000,
    designer: 'KNOTCRAFTSBYLA',
    category: 'Clothing',
    subcategory: 'Tops',
    gender: 'women',
    sizes: ['XS', 'S', 'M', 'L'],
  },
  {
    id: 'wcloth-4',
    name: 'Modern Kimono Jacket',
    image: '/images/category-kimonos.jpg',
    price: 60000,
    designer: 'JUST NOBLE COLLECTION',
    category: 'Clothing',
    subcategory: 'Kimonos',
    gender: 'women',
  },
  {
    id: 'wcloth-5',
    name: 'Stylish Ankara Jumpsuit',
    image: '/images/product-new-in-2.jpg',
    price: 55000,
    designer: 'AD_LINECLOTHING',
    category: 'Clothing',
    subcategory: 'Jumpsuits',
    gender: 'women',
  },
  {
    id: 'wcloth-6',
    name: 'Floral African Print Blouse',
    image: '/images/product-clothing-1.jpg',
    price: 68000,
    designer: 'HOUSE OF TYS AND MORE',
    category: 'Clothing',
    subcategory: 'Tops',
    gender: 'women',
  },
  {
    id: 'wcloth-7',
    name: 'Elegant Evening Gown',
    image: '/images/category-dresses.jpg',
    price: 85000,
    designer: 'ADIRE BUTIK',
    category: 'Clothing',
    subcategory: 'Dresses',
    gender: 'women',
    occasion: 'formal',
  },
  {
    id: 'wcloth-8',
    name: 'Casual Day Dress',
    image: '/images/shopby-casualwear.jpg',
    price: 42000,
    designer: 'IDOWU COUTURE AND WEARS',
    category: 'Clothing',
    subcategory: 'Dresses',
    gender: 'women',
    occasion: 'casual',
  },
  {
    id: 'wcloth-9',
    name: 'Office Chic Blouse',
    image: '/images/shopby-workwear.jpg',
    price: 38000,
    designer: 'KNOTCRAFTSBYLA',
    category: 'Clothing',
    subcategory: 'Tops',
    gender: 'women',
    occasion: 'work',
  },
  {
    id: 'wcloth-10',
    name: 'Party Sequin Dress',
    image: '/images/shopby-partywear.jpg',
    price: 95000,
    designer: 'JUST NOBLE COLLECTION',
    category: 'Clothing',
    subcategory: 'Dresses',
    gender: 'women',
    occasion: 'party',
  },
  {
    id: 'wcloth-11',
    name: 'Beach Cover-Up',
    image: '/images/shopby-beachwear.jpg',
    price: 35000,
    designer: 'AD_LINECLOTHING',
    category: 'Clothing',
    subcategory: 'Beachwear',
    gender: 'women',
    occasion: 'beach',
  },
  {
    id: 'wcloth-12',
    name: 'Wedding Guest Outfit',
    image: '/images/shopby-wedding.jpg',
    price: 120000,
    designer: 'HOUSE OF TYS AND MORE',
    category: 'Clothing',
    subcategory: 'Dresses',
    gender: 'women',
    occasion: 'wedding',
  },
];

// Men's Clothing Products
export const menClothingProducts: Product[] = [
  {
    id: 'mcloth-1',
    name: 'Traditional Kaftan',
    image: '/images/product-men-clothing-1.jpg',
    price: 55000,
    designer: 'ADIRE BUTIK',
    category: 'Clothing',
    subcategory: 'Kaftan',
    gender: 'men',
    isNew: true,
    sizes: ['M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'mcloth-2',
    name: 'Modern Dashiki Shirt',
    image: '/images/product-men-clothing-2.jpg',
    price: 35000,
    designer: 'IDOWU COUTURE AND WEARS',
    category: 'Clothing',
    subcategory: 'Shirts',
    gender: 'men',
    isNew: true,
  },
  {
    id: 'mcloth-3',
    name: 'Royal Agbada Complete',
    image: '/images/product-men-clothing-3.jpg',
    price: 125000,
    designer: 'KNOTCRAFTSBYLA',
    category: 'Clothing',
    subcategory: 'Agbada',
    gender: 'men',
    isFeatured: true,
  },
  {
    id: 'mcloth-4',
    name: 'Embroidered Senator',
    image: '/images/product-clothing-2.jpg',
    price: 65000,
    designer: 'JUST NOBLE COLLECTION',
    category: 'Clothing',
    subcategory: 'Senator',
    gender: 'men',
  },
  {
    id: 'mcloth-5',
    name: 'Casual African Shirt',
    image: '/images/product-men-clothing-2.jpg',
    price: 28000,
    designer: 'AD_LINECLOTHING',
    category: 'Clothing',
    subcategory: 'Shirts',
    gender: 'men',
    occasion: 'casual',
  },
  {
    id: 'mcloth-6',
    name: 'Formal Agbada Set',
    image: '/images/product-men-clothing-3.jpg',
    price: 150000,
    designer: 'HOUSE OF TYS AND MORE',
    category: 'Clothing',
    subcategory: 'Agbada',
    gender: 'men',
    occasion: 'formal',
  },
  {
    id: 'mcloth-7',
    name: 'Wedding Agbada',
    image: '/images/product-clothing-2.jpg',
    price: 180000,
    designer: 'ADIRE BUTIK',
    category: 'Clothing',
    subcategory: 'Agbada',
    gender: 'men',
    occasion: 'wedding',
  },
  {
    id: 'mcloth-8',
    name: 'Party Kaftan',
    image: '/images/product-men-clothing-1.jpg',
    price: 75000,
    designer: 'IDOWU COUTURE AND WEARS',
    category: 'Clothing',
    subcategory: 'Kaftan',
    gender: 'men',
    occasion: 'party',
  },
  {
    id: 'mcloth-9',
    name: 'Work African Shirt',
    image: '/images/product-men-clothing-2.jpg',
    price: 32000,
    designer: 'KNOTCRAFTSBYLA',
    category: 'Clothing',
    subcategory: 'Shirts',
    gender: 'men',
    occasion: 'work',
  },
  {
    id: 'mcloth-10',
    name: 'Loose Fit Boubou',
    image: '/images/product-men-clothing-1.jpg',
    price: 48000,
    designer: 'JUST NOBLE COLLECTION',
    category: 'Clothing',
    subcategory: 'Boubous',
    gender: 'men',
  },
  {
    id: 'mcloth-11',
    name: 'Regular Fit Senator',
    image: '/images/product-clothing-2.jpg',
    price: 58000,
    designer: 'AD_LINECLOTHING',
    category: 'Clothing',
    subcategory: 'Senator',
    gender: 'men',
  },
  {
    id: 'mcloth-12',
    name: 'Premium Embroidered Kaftan',
    image: '/images/product-men-clothing-3.jpg',
    price: 95000,
    designer: 'HOUSE OF TYS AND MORE',
    category: 'Clothing',
    subcategory: 'Kaftan',
    gender: 'men',
  },
];

// Kids Products
export const kidsProducts: Product[] = [
  {
    id: 'kid-1',
    name: 'Colorful Ankara Kids Outfit',
    image: '/images/product-kids-1.jpg',
    price: 25000,
    designer: 'ADIRE BUTIK',
    category: 'Kids',
    subcategory: 'Outfits',
    gender: 'kids',
    isNew: true,
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
  },
  {
    id: 'kid-2',
    name: 'Boys Traditional Kaftan',
    image: '/images/product-kids-2.jpg',
    price: 28000,
    designer: 'IDOWU COUTURE AND WEARS',
    category: 'Kids',
    subcategory: 'Boys',
    gender: 'kids',
    isNew: true,
  },
  {
    id: 'kid-3',
    name: 'Girls Ankara Dress',
    image: '/images/product-kids-3.jpg',
    price: 22000,
    designer: 'KNOTCRAFTSBYLA',
    category: 'Kids',
    subcategory: 'Girls',
    gender: 'kids',
  },
  {
    id: 'kid-4',
    name: 'Matching Siblings Set',
    image: '/images/product-kids-4.jpg',
    price: 45000,
    designer: 'JUST NOBLE COLLECTION',
    category: 'Kids',
    subcategory: 'Sets',
    gender: 'kids',
    isFeatured: true,
  },
  {
    id: 'kid-5',
    name: 'Kids Party Outfit',
    image: '/images/product-kids-1.jpg',
    price: 32000,
    designer: 'AD_LINECLOTHING',
    category: 'Kids',
    subcategory: 'Party',
    gender: 'kids',
    occasion: 'party',
  },
  {
    id: 'kid-6',
    name: 'Boys Dashiki Shirt',
    image: '/images/product-kids-2.jpg',
    price: 18000,
    designer: 'HOUSE OF TYS AND MORE',
    category: 'Kids',
    subcategory: 'Boys',
    gender: 'kids',
  },
  {
    id: 'kid-7',
    name: 'Girls Boubou Dress',
    image: '/images/product-kids-3.jpg',
    price: 26000,
    designer: 'ADIRE BUTIK',
    category: 'Kids',
    subcategory: 'Girls',
    gender: 'kids',
  },
  {
    id: 'kid-8',
    name: 'Kids Wedding Outfit',
    image: '/images/product-kids-4.jpg',
    price: 55000,
    designer: 'IDOWU COUTURE AND WEARS',
    category: 'Kids',
    subcategory: 'Formal',
    gender: 'kids',
    occasion: 'wedding',
  },
  {
    id: 'kid-9',
    name: 'Casual Kids Ankara',
    image: '/images/product-kids-1.jpg',
    price: 20000,
    designer: 'KNOTCRAFTSBYLA',
    category: 'Kids',
    subcategory: 'Casual',
    gender: 'kids',
    occasion: 'casual',
  },
  {
    id: 'kid-10',
    name: 'Boys Agbada Mini',
    image: '/images/product-kids-2.jpg',
    price: 48000,
    designer: 'JUST NOBLE COLLECTION',
    category: 'Kids',
    subcategory: 'Boys',
    gender: 'kids',
    occasion: 'formal',
  },
  {
    id: 'kid-11',
    name: 'Girls Traditional Set',
    image: '/images/product-kids-3.jpg',
    price: 35000,
    designer: 'AD_LINECLOTHING',
    category: 'Kids',
    subcategory: 'Girls',
    gender: 'kids',
  },
  {
    id: 'kid-12',
    name: 'Kids Birthday Outfit',
    image: '/images/product-kids-4.jpg',
    price: 38000,
    designer: 'HOUSE OF TYS AND MORE',
    category: 'Kids',
    subcategory: 'Party',
    gender: 'kids',
    occasion: 'party',
  },
];

// Shoes Products (Women)
export const womenShoesProducts: Product[] = [
  {
    id: 'wshoe-1',
    name: 'Luxury Beaded African Sandals',
    image: '/images/product-shoes-1.jpg',
    price: 28000,
    designer: 'ADIRE BUTIK',
    category: 'Shoes',
    gender: 'women',
    isNew: true,
  },
  {
    id: 'wshoe-2',
    name: 'Elegant Heeled Shoes - Gold & Black',
    image: '/images/product-shoes-2.jpg',
    price: 35000,
    designer: 'IDOWU COUTURE AND WEARS',
    category: 'Shoes',
    gender: 'women',
    isNew: true,
  },
  {
    id: 'wshoe-3',
    name: 'Luxury African Flat Sandals',
    image: '/images/product-shoes-3.jpg',
    price: 26000,
    designer: 'KNOTCRAFTSBYLA',
    category: 'Shoes',
    gender: 'women',
  },
  {
    id: 'wshoe-4',
    name: 'Statement Heels',
    image: '/images/product-shoes-2.jpg',
    price: 42000,
    designer: 'JUST NOBLE COLLECTION',
    category: 'Shoes',
    gender: 'women',
  },
  {
    id: 'wshoe-5',
    name: 'Casual Beaded Flats',
    image: '/images/product-shoes-1.jpg',
    price: 24000,
    designer: 'AD_LINECLOTHING',
    category: 'Shoes',
    gender: 'women',
  },
  {
    id: 'wshoe-6',
    name: 'Party Heels',
    image: '/images/product-shoes-2.jpg',
    price: 48000,
    designer: 'HOUSE OF TYS AND MORE',
    category: 'Shoes',
    gender: 'women',
    occasion: 'party',
  },
  {
    id: 'wshoe-7',
    name: 'Wedding Sandals',
    image: '/images/product-shoes-3.jpg',
    price: 55000,
    designer: 'ADIRE BUTIK',
    category: 'Shoes',
    gender: 'women',
    occasion: 'wedding',
  },
  {
    id: 'wshoe-8',
    name: 'Work Pumps',
    image: '/images/product-shoes-2.jpg',
    price: 38000,
    designer: 'IDOWU COUTURE AND WEARS',
    category: 'Shoes',
    gender: 'women',
    occasion: 'work',
  },
  {
    id: 'wshoe-9',
    name: 'Beach Sandals',
    image: '/images/product-shoes-1.jpg',
    price: 22000,
    designer: 'KNOTCRAFTSBYLA',
    category: 'Shoes',
    gender: 'women',
    occasion: 'beach',
  },
  {
    id: 'wshoe-10',
    name: 'Formal Heels',
    image: '/images/product-shoes-2.jpg',
    price: 45000,
    designer: 'JUST NOBLE COLLECTION',
    category: 'Shoes',
    gender: 'women',
    occasion: 'formal',
  },
  {
    id: 'wshoe-11',
    name: 'Everyday Flats',
    image: '/images/product-shoes-3.jpg',
    price: 20000,
    designer: 'AD_LINECLOTHING',
    category: 'Shoes',
    gender: 'women',
    occasion: 'casual',
  },
  {
    id: 'wshoe-12',
    name: 'Premium Heeled Sandals',
    image: '/images/product-shoes-1.jpg',
    price: 52000,
    designer: 'HOUSE OF TYS AND MORE',
    category: 'Shoes',
    gender: 'women',
  },
];

// Men's Shoes Products
export const menShoesProducts: Product[] = [
  {
    id: 'mshoe-1',
    name: 'Traditional Leather Slippers',
    image: '/images/product-men-shoes-1.jpg',
    price: 25000,
    designer: 'ADIRE BUTIK',
    category: 'Shoes',
    gender: 'men',
    isNew: true,
  },
  {
    id: 'mshoe-2',
    name: 'Handcrafted Sandals',
    image: '/images/product-men-shoes-1.jpg',
    price: 28000,
    designer: 'IDOWU COUTURE AND WEARS',
    category: 'Shoes',
    gender: 'men',
  },
  {
    id: 'mshoe-3',
    name: 'Formal Leather Shoes',
    image: '/images/product-men-shoes-1.jpg',
    price: 45000,
    designer: 'KNOTCRAFTSBYLA',
    category: 'Shoes',
    gender: 'men',
    occasion: 'formal',
  },
  {
    id: 'mshoe-4',
    name: 'Casual Loafers',
    image: '/images/product-men-shoes-1.jpg',
    price: 32000,
    designer: 'JUST NOBLE COLLECTION',
    category: 'Shoes',
    gender: 'men',
    occasion: 'casual',
  },
  {
    id: 'mshoe-5',
    name: 'Traditional Wedding Shoes',
    image: '/images/product-men-shoes-1.jpg',
    price: 55000,
    designer: 'AD_LINECLOTHING',
    category: 'Shoes',
    gender: 'men',
    occasion: 'wedding',
  },
  {
    id: 'mshoe-6',
    name: 'Premium Leather Slippers',
    image: '/images/product-men-shoes-1.jpg',
    price: 38000,
    designer: 'HOUSE OF TYS AND MORE',
    category: 'Shoes',
    gender: 'men',
  },
];

// Bags Products
export const bagsProducts: Product[] = [
  {
    id: 'bag-1',
    name: 'Luxury Leather Handbag - African Patterns',
    image: '/images/product-bags-1.jpg',
    price: 55000,
    designer: 'ADIRE BUTIK',
    category: 'Bags',
    gender: 'women',
    isNew: true,
  },
  {
    id: 'bag-2',
    name: 'Premium Woven African Basket Bag',
    image: '/images/product-bags-2.jpg',
    price: 42000,
    designer: 'IDOWU COUTURE AND WEARS',
    category: 'Bags',
    gender: 'women',
    isNew: true,
  },
  {
    id: 'bag-3',
    name: 'Designer Crossbody Bag with African Print',
    image: '/images/product-bags-3.jpg',
    price: 52000,
    designer: 'KNOTCRAFTSBYLA',
    category: 'Bags',
    gender: 'women',
  },
  {
    id: 'bag-4',
    name: 'Elegant Clutch Bag',
    image: '/images/product-bags-1.jpg',
    price: 35000,
    designer: 'JUST NOBLE COLLECTION',
    category: 'Bags',
    gender: 'women',
    occasion: 'party',
  },
  {
    id: 'bag-5',
    name: 'Work Tote Bag',
    image: '/images/product-bags-2.jpg',
    price: 48000,
    designer: 'AD_LINECLOTHING',
    category: 'Bags',
    gender: 'women',
    occasion: 'work',
  },
  {
    id: 'bag-6',
    name: 'Beach Basket Bag',
    image: '/images/product-bags-3.jpg',
    price: 38000,
    designer: 'HOUSE OF TYS AND MORE',
    category: 'Bags',
    gender: 'women',
    occasion: 'beach',
  },
  {
    id: 'bag-7',
    name: 'Wedding Clutch',
    image: '/images/product-bags-1.jpg',
    price: 65000,
    designer: 'ADIRE BUTIK',
    category: 'Bags',
    gender: 'women',
    occasion: 'wedding',
  },
  {
    id: 'bag-8',
    name: 'Everyday Crossbody',
    image: '/images/product-bags-2.jpg',
    price: 32000,
    designer: 'IDOWU COUTURE AND WEARS',
    category: 'Bags',
    gender: 'women',
    occasion: 'casual',
  },
  {
    id: 'bag-9',
    name: 'Designer Tote',
    image: '/images/product-bags-3.jpg',
    price: 75000,
    designer: 'KNOTCRAFTSBYLA',
    category: 'Bags',
    gender: 'women',
    isFeatured: true,
  },
  {
    id: 'bag-10',
    name: 'Mini Shoulder Bag',
    image: '/images/product-bags-1.jpg',
    price: 28000,
    designer: 'JUST NOBLE COLLECTION',
    category: 'Bags',
    gender: 'women',
  },
  {
    id: 'bag-11',
    name: 'Statement Handbag',
    image: '/images/product-bags-2.jpg',
    price: 58000,
    designer: 'AD_LINECLOTHING',
    category: 'Bags',
    gender: 'women',
  },
  {
    id: 'bag-12',
    name: 'Premium Leather Bag',
    image: '/images/product-bags-3.jpg',
    price: 85000,
    designer: 'HOUSE OF TYS AND MORE',
    category: 'Bags',
    gender: 'women',
  },
];

// Jewelry Products
export const jewelryProducts: Product[] = [
  {
    id: 'jew-1',
    name: 'Luxury Gold & Beaded African Jewelry Set',
    image: '/images/product-jewelry-1.jpg',
    price: 38000,
    designer: 'ADIRE BUTIK',
    category: 'Jewellery',
    gender: 'women',
    isNew: true,
  },
  {
    id: 'jew-2',
    name: 'Elegant Beaded African Bracelets & Rings',
    image: '/images/product-jewelry-2.jpg',
    price: 22000,
    designer: 'IDOWU COUTURE AND WEARS',
    category: 'Jewellery',
    gender: 'women',
    isNew: true,
  },
  {
    id: 'jew-3',
    name: 'Statement Golden Earrings',
    image: '/images/product-jewelry-3.jpg',
    price: 36000,
    designer: 'KNOTCRAFTSBYLA',
    category: 'Jewellery',
    gender: 'women',
  },
  {
    id: 'jew-4',
    name: 'Wedding Jewelry Set',
    image: '/images/product-jewelry-1.jpg',
    price: 85000,
    designer: 'JUST NOBLE COLLECTION',
    category: 'Jewellery',
    gender: 'women',
    occasion: 'wedding',
  },
  {
    id: 'jew-5',
    name: 'Party Statement Necklace',
    image: '/images/product-jewelry-2.jpg',
    price: 45000,
    designer: 'AD_LINECLOTHING',
    category: 'Jewellery',
    gender: 'women',
    occasion: 'party',
  },
  {
    id: 'jew-6',
    name: 'Everyday Bracelet Set',
    image: '/images/product-jewelry-3.jpg',
    price: 18000,
    designer: 'HOUSE OF TYS AND MORE',
    category: 'Jewellery',
    gender: 'women',
    occasion: 'casual',
  },
  {
    id: 'jew-7',
    name: 'Formal Jewelry Set',
    image: '/images/product-jewelry-1.jpg',
    price: 55000,
    designer: 'ADIRE BUTIK',
    category: 'Jewellery',
    gender: 'women',
    occasion: 'formal',
  },
  {
    id: 'jew-8',
    name: 'Traditional Coral Beads',
    image: '/images/product-jewelry-2.jpg',
    price: 120000,
    designer: 'IDOWU COUTURE AND WEARS',
    category: 'Jewellery',
    gender: 'women',
    isFeatured: true,
  },
  {
    id: 'jew-9',
    name: 'Gold Pendant Necklace',
    image: '/images/product-jewelry-3.jpg',
    price: 32000,
    designer: 'KNOTCRAFTSBYLA',
    category: 'Jewellery',
    gender: 'women',
  },
  {
    id: 'jew-10',
    name: 'Beaded Anklet Set',
    image: '/images/product-jewelry-1.jpg',
    price: 15000,
    designer: 'JUST NOBLE COLLECTION',
    category: 'Jewellery',
    gender: 'women',
  },
  {
    id: 'jew-11',
    name: 'Statement Ring Collection',
    image: '/images/product-jewelry-2.jpg',
    price: 28000,
    designer: 'AD_LINECLOTHING',
    category: 'Jewellery',
    gender: 'women',
  },
  {
    id: 'jew-12',
    name: 'Premium Earring Set',
    image: '/images/product-jewelry-3.jpg',
    price: 42000,
    designer: 'HOUSE OF TYS AND MORE',
    category: 'Jewellery',
    gender: 'women',
  },
];

// Accessories Products
export const accessoriesProducts: Product[] = [
  {
    id: 'acc-1',
    name: 'Colorful African Print Head Wraps & Scarves',
    image: '/images/product-accessories-1.jpg',
    price: 12000,
    designer: 'ADIRE BUTIK',
    category: 'Accessories',
    gender: 'women',
    isNew: true,
  },
  {
    id: 'acc-2',
    name: 'Luxury African Hat & Shawl Set',
    image: '/images/product-accessories-2.jpg',
    price: 18000,
    designer: 'IDOWU COUTURE AND WEARS',
    category: 'Accessories',
    gender: 'women',
    isNew: true,
  },
  {
    id: 'acc-3',
    name: 'Traditional Gele Headwrap',
    image: '/images/product-accessories-1.jpg',
    price: 25000,
    designer: 'KNOTCRAFTSBYLA',
    category: 'Accessories',
    gender: 'women',
    occasion: 'wedding',
  },
  {
    id: 'acc-4',
    name: 'Fashion Scarf',
    image: '/images/product-accessories-2.jpg',
    price: 15000,
    designer: 'JUST NOBLE COLLECTION',
    category: 'Accessories',
    gender: 'women',
    occasion: 'casual',
  },
  {
    id: 'acc-5',
    name: 'Beach Hat',
    image: '/images/product-accessories-1.jpg',
    price: 20000,
    designer: 'AD_LINECLOTHING',
    category: 'Accessories',
    gender: 'women',
    occasion: 'beach',
  },
  {
    id: 'acc-6',
    name: 'Party Fascinator',
    image: '/images/product-accessories-2.jpg',
    price: 35000,
    designer: 'HOUSE OF TYS AND MORE',
    category: 'Accessories',
    gender: 'women',
    occasion: 'party',
  },
  {
    id: 'acc-7',
    name: 'Work Belt',
    image: '/images/product-accessories-1.jpg',
    price: 22000,
    designer: 'ADIRE BUTIK',
    category: 'Accessories',
    gender: 'women',
    occasion: 'work',
  },
  {
    id: 'acc-8',
    name: 'Sunglasses',
    image: '/images/product-accessories-2.jpg',
    price: 28000,
    designer: 'IDOWU COUTURE AND WEARS',
    category: 'Accessories',
    gender: 'unisex',
  },
  {
    id: 'acc-9',
    name: 'Formal Gloves',
    image: '/images/product-accessories-1.jpg',
    price: 18000,
    designer: 'KNOTCRAFTSBYLA',
    category: 'Accessories',
    gender: 'women',
    occasion: 'formal',
  },
];

// Men's Accessories Products
export const menAccessoriesProducts: Product[] = [
  {
    id: 'macc-1',
    name: 'Traditional Fila Cap',
    image: '/images/product-men-accessories-1.jpg',
    price: 15000,
    designer: 'ADIRE BUTIK',
    category: 'Accessories',
    gender: 'men',
    isNew: true,
  },
  {
    id: 'macc-2',
    name: 'Embroidered Cap',
    image: '/images/product-men-accessories-1.jpg',
    price: 18000,
    designer: 'IDOWU COUTURE AND WEARS',
    category: 'Accessories',
    gender: 'men',
  },
  {
    id: 'macc-3',
    name: 'Wedding Fila',
    image: '/images/product-men-accessories-1.jpg',
    price: 25000,
    designer: 'KNOTCRAFTSBYLA',
    category: 'Accessories',
    gender: 'men',
    occasion: 'wedding',
  },
  {
    id: 'macc-4',
    name: 'Casual Cap',
    image: '/images/product-men-accessories-1.jpg',
    price: 12000,
    designer: 'JUST NOBLE COLLECTION',
    category: 'Accessories',
    gender: 'men',
    occasion: 'casual',
  },
  {
    id: 'macc-5',
    name: 'Traditional Beads',
    image: '/images/product-jewelry-1.jpg',
    price: 35000,
    designer: 'AD_LINECLOTHING',
    category: 'Accessories',
    gender: 'men',
    occasion: 'formal',
  },
  {
    id: 'macc-6',
    name: 'Leather Belt',
    image: '/images/product-men-accessories-1.jpg',
    price: 22000,
    designer: 'HOUSE OF TYS AND MORE',
    category: 'Accessories',
    gender: 'men',
  },
];

// Beauty Products
export const beautyProducts: Product[] = [
  {
    id: 'beauty-1',
    name: 'Natural Shea Butter Cream',
    image: '/images/product-beauty-1.jpg',
    price: 8500,
    designer: 'ARTISAN BEAUTY',
    category: 'Beauty',
    gender: 'unisex',
    isNew: true,
  },
  {
    id: 'beauty-2',
    name: 'Hair Care Oil Set',
    image: '/images/product-beauty-2.jpg',
    price: 12000,
    designer: 'NATURAL GLOW',
    category: 'Beauty',
    gender: 'unisex',
    isNew: true,
  },
  {
    id: 'beauty-3',
    name: 'African Black Soap',
    image: '/images/product-beauty-1.jpg',
    price: 5000,
    designer: 'ARTISAN BEAUTY',
    category: 'Beauty',
    gender: 'unisex',
  },
  {
    id: 'beauty-4',
    name: 'Body Butter',
    image: '/images/product-beauty-2.jpg',
    price: 9500,
    designer: 'NATURAL GLOW',
    category: 'Beauty',
    gender: 'unisex',
  },
  {
    id: 'beauty-5',
    name: 'Hair Growth Oil',
    image: '/images/product-beauty-1.jpg',
    price: 15000,
    designer: 'ARTISAN BEAUTY',
    category: 'Beauty',
    gender: 'unisex',
  },
  {
    id: 'beauty-6',
    name: 'Moisturizing Lotion',
    image: '/images/product-beauty-2.jpg',
    price: 7500,
    designer: 'NATURAL GLOW',
    category: 'Beauty',
    gender: 'unisex',
  },
  {
    id: 'beauty-7',
    name: 'Face Cream',
    image: '/images/product-beauty-1.jpg',
    price: 11000,
    designer: 'ARTISAN BEAUTY',
    category: 'Beauty',
    gender: 'unisex',
  },
  {
    id: 'beauty-8',
    name: 'Essential Oil Set',
    image: '/images/product-beauty-2.jpg',
    price: 18000,
    designer: 'NATURAL GLOW',
    category: 'Beauty',
    gender: 'unisex',
  },
];

// Homeware Products
export const homewareProducts: Product[] = [
  {
    id: 'home-1',
    name: 'Premium Linen Throw Pillow - Ochre',
    image: '/images/product-homeware-1.jpg',
    price: 15000,
    designer: 'ARTISAN HOME COLLECTIVE',
    category: 'Homeware',
    subcategory: 'Textiles',
    isNew: true,
  },
  {
    id: 'home-2',
    name: 'Hand-Woven Wall Hanging Tapestry',
    image: '/images/product-homeware-2.jpg',
    price: 28000,
    designer: 'TEXTILE TRADITIONS',
    category: 'Homeware',
    subcategory: 'Decor',
    isNew: true,
  },
  {
    id: 'home-3',
    name: 'Natural Rattan Storage Baskets Set',
    image: '/images/product-homeware-3.jpg',
    price: 32000,
    designer: 'SUSTAINABLE LIVING CO',
    category: 'Homeware',
    subcategory: 'Decor',
  },
  {
    id: 'home-4',
    name: 'Ceramic Dinner Set - Handcrafted',
    image: '/images/product-homeware-4.jpg',
    price: 45000,
    designer: 'POTTERY MASTERS',
    category: 'Homeware',
    subcategory: 'Kitchen',
  },
  {
    id: 'home-5',
    name: 'Brass & Wood Coffee Table',
    image: '/images/product-homeware-5.jpg',
    price: 85000,
    designer: 'ARTISAN HOME COLLECTIVE',
    category: 'Homeware',
    subcategory: 'Furniture',
    isFeatured: true,
  },
  {
    id: 'home-6',
    name: 'Organic Cotton Bedding Collection',
    image: '/images/product-homeware-6.jpg',
    price: 38000,
    designer: 'TEXTILE TRADITIONS',
    category: 'Homeware',
    subcategory: 'Textiles',
  },
  {
    id: 'home-7',
    name: 'Pendant Lighting - Beaded Glass',
    image: '/images/product-homeware-7.jpg',
    price: 22000,
    designer: 'LIGHTING DESIGNS',
    category: 'Homeware',
    subcategory: 'Lighting',
  },
  {
    id: 'home-8',
    name: 'Wooden Kitchen Utensil Set',
    image: '/images/product-homeware-8.jpg',
    price: 18000,
    designer: 'KITCHEN ARTISANS',
    category: 'Homeware',
    subcategory: 'Kitchen',
  },
  {
    id: 'home-9',
    name: 'Area Rug - African Patterns',
    image: '/images/product-homeware-9.jpg',
    price: 95000,
    designer: 'WOVEN HERITAGE',
    category: 'Homeware',
    subcategory: 'Textiles',
    isFeatured: true,
  },
  {
    id: 'home-10',
    name: 'Decorative Mirror - Metal Frame',
    image: '/images/product-homeware-10.jpg',
    price: 24000,
    designer: 'ARTISAN HOME COLLECTIVE',
    category: 'Homeware',
    subcategory: 'Decor',
  },
  {
    id: 'home-11',
    name: 'Stoneware Vase Collection',
    image: '/images/product-homeware-11.jpg',
    price: 19000,
    designer: 'POTTERY MASTERS',
    category: 'Homeware',
    subcategory: 'Decor',
  },
  {
    id: 'home-12',
    name: 'Sustainable Bamboo Furniture Set',
    image: '/images/product-homeware-12.jpg',
    price: 125000,
    designer: 'SUSTAINABLE LIVING CO',
    category: 'Homeware',
    subcategory: 'Furniture',
    isFeatured: true,
  },
];

// Designer Products
export const designerProducts: Product[] = [
  {
    id: 'des-1',
    name: 'Premium African Designer Fashion Piece',
    image: '/images/product-designer-1.jpg',
    price: 95000,
    designer: 'ADIRE BUTIK',
    category: 'Designer',
    gender: 'women',
    isFeatured: true,
  },
  {
    id: 'des-2',
    name: 'Exclusive African Designer Dress',
    image: '/images/product-designer-2.jpg',
    price: 120000,
    designer: 'IDOWU COUTURE AND WEARS',
    category: 'Designer',
    gender: 'women',
    isFeatured: true,
  },
  {
    id: 'des-3',
    name: 'Haute Couture Gown',
    image: '/images/product-designer-1.jpg',
    price: 250000,
    designer: 'KNOTCRAFTSBYLA',
    category: 'Designer',
    gender: 'women',
    isFeatured: true,
  },
  {
    id: 'des-4',
    name: 'Designer Agbada Set',
    image: '/images/product-men-clothing-3.jpg',
    price: 180000,
    designer: 'JUST NOBLE COLLECTION',
    category: 'Designer',
    gender: 'men',
    isFeatured: true,
  },
  {
    id: 'des-5',
    name: 'Luxury Evening Gown',
    image: '/images/product-designer-2.jpg',
    price: 200000,
    designer: 'AD_LINECLOTHING',
    category: 'Designer',
    gender: 'women',
    isFeatured: true,
  },
  {
    id: 'des-6',
    name: 'Designer Kaftan',
    image: '/images/product-men-clothing-1.jpg',
    price: 150000,
    designer: 'HOUSE OF TYS AND MORE',
    category: 'Designer',
    gender: 'men',
    isFeatured: true,
  },
];

// New In Products (combining all new items)
export const newInProducts: Product[] = [
  ...womenClothingProducts.filter(p => p.isNew),
  ...menClothingProducts.filter(p => p.isNew),
  ...kidsProducts.filter(p => p.isNew),
  ...womenShoesProducts.filter(p => p.isNew),
  ...bagsProducts.filter(p => p.isNew),
  ...jewelryProducts.filter(p => p.isNew),
  ...accessoriesProducts.filter(p => p.isNew),
  ...homewareProducts.filter(p => p.isNew),
  ...beautyProducts.filter(p => p.isNew),
];

// Backward compatibility exports
export const clothingProducts = womenClothingProducts;
export const shoesProducts = womenShoesProducts;
export const kidsClothingProducts = kidsProducts;

// All products combined
export const allProducts: Product[] = [
  ...womenClothingProducts,
  ...menClothingProducts,
  ...kidsProducts,
  ...womenShoesProducts,
  ...menShoesProducts,
  ...bagsProducts,
  ...jewelryProducts,
  ...accessoriesProducts,
  ...menAccessoriesProducts,
  ...beautyProducts,
  ...homewareProducts,
  ...designerProducts,
];

// Helper functions
export const getProductsByCategory = (category: string): Product[] => {
  return allProducts.filter(p => p.category.toLowerCase() === category.toLowerCase());
};

export const getProductsByGender = (gender: 'women' | 'men' | 'kids' | 'unisex'): Product[] => {
  return allProducts.filter(p => p.gender === gender || p.gender === 'unisex');
};

export const getProductsByOccasion = (occasion: string): Product[] => {
  return allProducts.filter(p => p.occasion?.toLowerCase() === occasion.toLowerCase());
};

export const getProductById = (id: string): Product | undefined => {
  return allProducts.find(p => p.id === id);
};

export const getProductsByDesigner = (designer: string): Product[] => {
  return allProducts.filter(p => p.designer === designer);
};

// Get products by shop-by category
export const getProductsByShopBy = (slug: string): Product[] => {
  const category = shopByCategories.find(cat => cat.slug === slug);
  if (!category) return allProducts;
  
  // Map slug to occasion field
  const occasionMap: { [key: string]: string } = {
    'beach-wear': 'beach',
    'casual-wear': 'casual',
    'formal-wear': 'formal',
    'loose-fit': 'loose',
    'party-wear': 'party',
    'regular-fit': 'regular',
    'sports-wear': 'sports',
    'tall': 'tall',
    'weddings': 'wedding',
    'work-wear': 'work',
    'working-out': 'workout',
  };
  
  const occasion = occasionMap[slug];
  if (!occasion) return allProducts;
  
  return allProducts.filter(p => p.occasion === occasion);
};

// Shop By Occasion mapping
export const shopByCategories = [
  { name: 'Beach Wear', slug: 'beach-wear', occasion: 'beach', image: '/images/shopby-beachwear.jpg' },
  { name: 'Casual Wear', slug: 'casual-wear', occasion: 'casual', image: '/images/shopby-casualwear.jpg' },
  { name: 'Formal Wear', slug: 'formal-wear', occasion: 'formal', image: '/images/shopby-formalwear.jpg' },
  { name: 'Loose Fit', slug: 'loose-fit', occasion: 'loose', image: '/images/shopby-loosefit.jpg' },
  { name: 'Party Wear', slug: 'party-wear', occasion: 'party', image: '/images/shopby-partywear.jpg' },
  { name: 'Regular Fit', slug: 'regular-fit', occasion: 'regular', image: '/images/shopby-regularfit.jpg' },
  { name: 'Sports Wear', slug: 'sports-wear', occasion: 'sports', image: '/images/shopby-sportswear.jpg' },
  { name: 'Tall', slug: 'tall', occasion: 'tall', image: '/images/shopby-tall.jpg' },
  { name: 'Weddings', slug: 'weddings', occasion: 'wedding', image: '/images/shopby-wedding.jpg' },
  { name: 'Work Wear', slug: 'work-wear', occasion: 'work', image: '/images/shopby-workwear.jpg' },
  { name: 'Working Out', slug: 'working-out', occasion: 'workout', image: '/images/shopby-workout.jpg' },
];

// Designers list
export const designers = [
  { name: 'ADIRE BUTIK', slug: 'adire-butik', logo: '/images/designers-hero.jpg' },
  { name: 'IDOWU COUTURE AND WEARS', slug: 'idowu-couture', logo: '/images/designers-hero.jpg' },
  { name: 'KNOTCRAFTSBYLA', slug: 'knotcraftsbyla', logo: '/images/designers-hero.jpg' },
  { name: 'JUST NOBLE COLLECTION', slug: 'just-noble', logo: '/images/designers-hero.jpg' },
  { name: 'AD_LINECLOTHING', slug: 'adline-clothing', logo: '/images/designers-hero.jpg' },
  { name: 'HOUSE OF TYS AND MORE', slug: 'house-of-tys', logo: '/images/designers-hero.jpg' },
  { name: 'MIEKO MICHI', slug: 'mieko-michi', logo: '/images/designers-hero.jpg' },
  { name: 'RAYHA SWISH EMPIRE', slug: 'rayha-swish', logo: '/images/designers-hero.jpg' },
  { name: 'LOHIJE', slug: 'lohije', logo: '/images/designers-hero.jpg' },
  { name: 'EYEZNIKA FASHION STUDIO', slug: 'eyeznika', logo: '/images/designers-hero.jpg' },
  { name: 'OMA APPAREL DESIGNS', slug: 'oma-apparel', logo: '/images/designers-hero.jpg' },
  { name: 'JAZZEFFECT DESIGN', slug: 'jazzeffect', logo: '/images/designers-hero.jpg' },
  { name: 'ARTISAN HOME COLLECTIVE', slug: 'artisan-home', logo: '/images/designers-hero.jpg' },
  { name: 'TEXTILE TRADITIONS', slug: 'textile-traditions', logo: '/images/designers-hero.jpg' },
  { name: 'SUSTAINABLE LIVING CO', slug: 'sustainable-living', logo: '/images/designers-hero.jpg' },
  { name: 'POTTERY MASTERS', slug: 'pottery-masters', logo: '/images/designers-hero.jpg' },
];
